env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      env: XCODE_VERSION=7.3
    - os: osx
      language: objective-c
      osx_image: xcode8
      env: XCODE_VERSION=8

script:
  - if [[ "$XCODE_VERISON" == "7.3" ]]; then  pod lib lint --allow-warnings; fi
  - set -o pipefail
  - xcodebuild build test -scheme DelegateProxy-macOS -configuration Release -sdk macosx -destination 'platform=OS X,arch=x86_64' | xcpretty -c
  - xcodebuild build test -scheme DelegateProxy-iOS -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty -c
  - xcodebuild build test -scheme DelegateProxy-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme DelegateProxy-watchOS -configuration Release -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' | xcpretty -c

notifications:
  email: false
